package br.com.efraimgentil.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-17T11:40:52.372-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://ws.efraimgentil.com.br/", name = "UserWS")
@XmlSeeAlso({ObjectFactory.class})
public interface UserWS {

    @RequestWrapper(localName = "addUser", targetNamespace = "http://ws.efraimgentil.com.br/", className = "br.com.efraimgentil.ws.AddUser")
    @WebMethod
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://ws.efraimgentil.com.br/", className = "br.com.efraimgentil.ws.AddUserResponse")
    public void addUser(
        @WebParam(name = "user", targetNamespace = "")
        br.com.efraimgentil.ws.User user
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findUser", targetNamespace = "http://ws.efraimgentil.com.br/", className = "br.com.efraimgentil.ws.FindUser")
    @WebMethod
    @ResponseWrapper(localName = "findUserResponse", targetNamespace = "http://ws.efraimgentil.com.br/", className = "br.com.efraimgentil.ws.FindUserResponse")
    public java.lang.String findUser(
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email
    );
}
