package br.com.efraimgentil.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-17T11:40:52.386-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "UserWSService", 
                  wsdlLocation = "http://localhost:8080/ws-ejb/UserWS?wsdl",
                  targetNamespace = "http://ws.efraimgentil.com.br/") 
public class UserWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.efraimgentil.com.br/", "UserWSService");
    public final static QName UserWSPort = new QName("http://ws.efraimgentil.com.br/", "UserWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws-ejb/UserWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws-ejb/UserWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public UserWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns UserWS
     */
    @WebEndpoint(name = "UserWSPort")
    public UserWS getUserWSPort() {
        return super.getPort(UserWSPort, UserWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWS
     */
    @WebEndpoint(name = "UserWSPort")
    public UserWS getUserWSPort(WebServiceFeature... features) {
        return super.getPort(UserWSPort, UserWS.class, features);
    }

}
