
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package br.com.efraimgentil.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-17T11:40:52.345-03:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "UserWSService",
                      portName = "UserWSPort",
                      targetNamespace = "http://ws.efraimgentil.com.br/",
                      wsdlLocation = "http://localhost:8080/ws-ejb/UserWS?wsdl",
                      endpointInterface = "br.com.efraimgentil.ws.UserWS")
                      
public class UserWSImpl implements UserWS {

    private static final Logger LOG = Logger.getLogger(UserWSImpl.class.getName());

    /* (non-Javadoc)
     * @see br.com.efraimgentil.ws.UserWS#addUser(br.com.efraimgentil.ws.User  user )*
     */
    public void addUser(br.com.efraimgentil.ws.User user) { 
        LOG.info("Executing operation addUser");
        System.out.println(user);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see br.com.efraimgentil.ws.UserWS#findUser(java.lang.String  email )*
     */
    public java.lang.String findUser(java.lang.String email) { 
        LOG.info("Executing operation findUser");
        System.out.println(email);
        try {
            java.lang.String _return = "_return1791504807";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
