package br.com.efraimgentil.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-20T21:34:34.992-03:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://ws.efraimgentil.com.br/", name = "ContasWs")
@XmlSeeAlso({ObjectFactory.class})
public interface ContasWs {

    @RequestWrapper(localName = "novo", targetNamespace = "http://ws.efraimgentil.com.br/", className = "br.com.efraimgentil.ws.Novo")
    @WebMethod
    @ResponseWrapper(localName = "novoResponse", targetNamespace = "http://ws.efraimgentil.com.br/", className = "br.com.efraimgentil.ws.NovoResponse")
    public void novo(
        @WebParam(name = "arg0", targetNamespace = "")
        br.com.efraimgentil.ws.Conta arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "aPagar", targetNamespace = "http://ws.efraimgentil.com.br/", className = "br.com.efraimgentil.ws.APagar")
    @WebMethod
    @ResponseWrapper(localName = "aPagarResponse", targetNamespace = "http://ws.efraimgentil.com.br/", className = "br.com.efraimgentil.ws.APagarResponse")
    public java.util.List<br.com.efraimgentil.ws.Conta> aPagar();
}
