
package br.com.efraimgentil.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-06-20T21:34:34.861-03:00
 * Generated source version: 2.7.11
 * 
 */
public final class ContasWs_ContasWsPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.efraimgentil.com.br/", "ContasWsService");

    private ContasWs_ContasWsPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ContasWsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ContasWsService ss = new ContasWsService(wsdlURL, SERVICE_NAME);
        ContasWs port = ss.getContasWsPort();  
        
        {
        System.out.println("Invoking novo...");
        br.com.efraimgentil.ws.Conta _novo_arg0 = new br.com.efraimgentil.ws.Conta();
        _novo_arg0.setCedente("Cedente-495827348");
        _novo_arg0.setDataPagamento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-06-20T21:34:34.950-03:00"));
        _novo_arg0.setDataVencimento(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2014-06-20T21:34:34.953-03:00"));
        _novo_arg0.setDescricao("Descricao1218301873");
        _novo_arg0.setId(Long.valueOf(4694120136554360634l));
        _novo_arg0.setValor(Double.valueOf(0.2760205396036173));
        _novo_arg0.setValorPago(Double.valueOf(0.5491261744307231));
        port.novo(_novo_arg0);


        }
        {
        System.out.println("Invoking aPagar...");
        java.util.List<br.com.efraimgentil.ws.Conta> _aPagar__return = port.aPagar();
        System.out.println("aPagar.result=" + _aPagar__return);


        }

        System.exit(0);
    }

}
